### ISSUE TITLE
Latest tag on RaspberryPi 4 gives error

### ISSUE THREAD

**Issue by mhoogenbosch** [mpepping/solarman-mqtt#16]
Error in my log shows: standard_init_linux.go:228: exec user process caused: exec format error

compose file i'm using:

  solarman-mqtt-test:
    image: ghcr.io/mpepping/solarman-mqtt:latest
    container_name: "solarman-mqtt-test"
    environment:
    - TZ=${TZ}
    mem_limit: 512m
    volumes:
      - ${DOCKERCONFDIR}/solarman-mqtt-test:/opt/app-root/src
    restart: unless-stopped

Any thoughts

**Comment by mpepping** [comment]
@mhoogenbosch I just tried to add arm64 support (#15), like just an hour or two ago. 
To clarify, did previous images work on the Pi4, or did you just tried today?

Pushed an update just now (`latest`, `v0.4.1`, `v0.4`). Can you give it a try?

**Comment by mhoogenbosch** [comment]
No I guess I used a fork. Wasn't aware of the fact I was using a fork. But I guess this was the reason? Don't know. Am testing now, thanks for your quick response!

**Comment by mpepping** [comment]
@mhoogenbosch Ah makes sense! I was doubting if there was some kind of automagic cross-arch support added in the GitHub Actions plugin. 

Can't test ARM64 support for myself, so thank you that you gave it a go. I merged ARM64 support, and according to the build logs, both an AMD64 and ARM64 are now available on the tag `latest` (`0.4`, `0.4.2`). 

If it isn't too much trouble, would you mind giving this one a try?

**Comment by mhoogenbosch** [comment]
> @mhoogenbosch Ah makes sense! I was doubting if there was some kind of automagic cross-arch support added in the GitHub Actions plugin.
> 
> Can't test ARM64 support for myself, so thank you that you gave it a go. I merged ARM64 support, and according to the build logs, both an AMD64 and ARM64 are now available on the tag `latest` (`0.4`, `0.4.2`).
> 
> If it isn't too much trouble, would you mind giving this one a try?

Seems to work! 
![image](https://user-images.githubusercontent.com/36899598/150698173-37b03252-b86a-4e1b-8f90-0993201157b0.png)

Thanks a lot

**Comment by mpepping** [comment]
Thanks, @mhoogenbosch!

**Comment by mhoogenbosch** [comment]
Sun is still not producing enough power to enable my inverter so haven't been able to see actual output, but will report back. Can't imagine it won't work.
